Fix import on Python 3.10 with numpy 1.26.4
Referencing numpy.typing without explicit import does not work.
Importing gsffile thus fails.

>>> import numpy as np
>>> np.__version__
'1.26.4'
>>> np.typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marko/venv310/lib/python3.10/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typing'. Did you mean: '_typing'?
>>> import numpy.typing
>>> np.typing
<module 'numpy.typing' from '/home/marko/venv310/lib/python3.10/site-packages/numpy/typing/__init__.py'>